services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:alpine-jdk21
    restart: always
    environment:
      - "TZ=Europe/Berlin"
      - "JAVA_OPTS=-Xmx256M -Xms256M"
    ports:
      - "127.0.0.1:8081:8080"
    volumes:
      - "/opt/jenkins:/var/jenkins_home"
    links:
      - jenkins-agent
    jenkins-agent:
      container_name: jenkins-agent
      image: zoeyvid/jenkins-ssh-agent
      restart: always
      environment:
        - "TZ=Europe/Berlin"
        - "SSH_PUBKEY=ssh-ed25519 ABCDEFGHIJKLMNOPQRSTUVWXYZ"
